// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2zoIdbgwa0X2s7gmSzSDFdytPZN2bLho',
    appId: '1:709304711003:web:5166389a6a913fbd4bcc7e',
    messagingSenderId: '709304711003',
    projectId: 'khelbindass99-277ce',
    authDomain: 'khelbindass99-277ce.firebaseapp.com',
    storageBucket: 'khelbindass99-277ce.firebasestorage.app',
    measurementId: 'G-FRV41FYC9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7FV89dj-jTXXzsXlGGb7s9UuR0KrvmMU',
    appId: '1:709304711003:android:19eb10bb5e4a06104bcc7e',
    messagingSenderId: '709304711003',
    projectId: 'khelbindass99-277ce',
    storageBucket: 'khelbindass99-277ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDZjQPWqCCCmqkuHcN7QlJs2xVOPwabgU',
    appId: '1:709304711003:ios:2ab7a07547dfe11d4bcc7e',
    messagingSenderId: '709304711003',
    projectId: 'khelbindass99-277ce',
    storageBucket: 'khelbindass99-277ce.firebasestorage.app',
    iosBundleId: 'com.example.khelbindass99',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDZjQPWqCCCmqkuHcN7QlJs2xVOPwabgU',
    appId: '1:709304711003:ios:2ab7a07547dfe11d4bcc7e',
    messagingSenderId: '709304711003',
    projectId: 'khelbindass99-277ce',
    storageBucket: 'khelbindass99-277ce.firebasestorage.app',
    iosBundleId: 'com.example.khelbindass99',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2zoIdbgwa0X2s7gmSzSDFdytPZN2bLho',
    appId: '1:709304711003:web:7d27328b6b15813b4bcc7e',
    messagingSenderId: '709304711003',
    projectId: 'khelbindass99-277ce',
    authDomain: 'khelbindass99-277ce.firebaseapp.com',
    storageBucket: 'khelbindass99-277ce.firebasestorage.app',
    measurementId: 'G-9P1TBZ29D2',
  );
}
